version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Entered the installing phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre build phase...
      - cd functions/sample-function
      - ls -lat
      - npm init -y
      - npm install -y
      - ls -lat
      - mv package* node_modules/ node_modules/* ../../dependencies/nodejs
    finally: 
      - echo This always runs even if the pre build phase commands fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - sam package --template-file ./CFNTemplates/lambda-stack/template.yaml --output-template-file ./CFNTemplates/lambda-stack/packaged-template.yaml --region ap-southeast-1 --resolve-s3 
    finally: 
      - echo This always runs even if the build phase commands fails
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Entered the post_build phase...
      - sam deploy --template-file ./CFNTemplates/lambda-stack/template.yaml --stack-name sample-lambda-layer-stack --capabilities CAPABILITY_IAM --region ap-southeast-1
      
artifacts:
  files:
    - "./CFNTemplates/lambda-stack/packaged-template.yaml"

# artifacts:
#   files:
#     - package.json
#     - Procfile
#     - src/index.js
#     - src/middlewares.js
#     - node_modules/**/*
#     - .eslintrc.js
#     - package-lock.json
#     - .env
#   name: express-miniapp
#   base-directory: express-miniapp

# cache:
#   paths:
#     - node_modules/**/*