version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Entered the installing phase...
      - apt install rsync -y
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre build phase...
      - npm prune
      - ls -lat
      # - if [ -d "dependencies/nodejs" ] &&  rm -rf dependencies/nodejs
      - mkdir -p dependencies/nodejs
      - cd functions/sample-function
      - ls -lat
      - npm install
      # - pwd
      - ls -lat
      # - mv -uf package* node_modules ../../dependencies/nodejs
      # prepare dependencies for lambda layers
      - rsync -a package* node_modules* ../../dependencies/nodejs/
      - rm -rf node_modules/
    finally: 
      - echo This always runs even if the pre build phase commands fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      
      #package layers
      # - sam package --template-file ../../CFNTemplates/lambda-layer-stack/template.yaml --output-template-file ../../CFNTemplates/lambda-layer-stack/packaged-template.yaml --region ap-southeast-1 --resolve-s3
      # #deploy layers
      # - sam deploy --template-file ../../CFNTemplates/lambda-layer-stack/packaged-template.yaml --stack-name samplelambdalayer --capabilities CAPABILITY_IAM --region ap-southeast-1
      
      #package lambda function
      - sam package --template-file ../../CFNTemplates/lambda-stack/template.yaml --output-template-file ../../CFNTemplates/lambda-stack/packaged-template.yaml --region ap-southeast-1 --resolve-s3 
    finally: 
      - echo This always runs even if the build phase commands fails
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Entered the post_build phase...
      
artifacts:
  files:
    - "packaged-template.yaml"
  base-directory: CFNTemplates/lambda-stack

cache:
  files:
    - '**/*'
