AWSTemplateFormatVersion: 2010-09-09
Description: "Test for Lambda Layers"
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    ArtifactBucket:
      Type: AWS::S3::Bucket
        
    
    CodePipelineServiceRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codepipeline.amazonaws.com
                  - codebuild.amazonaws.com
                  - codedeploy.amazonaws.com
                  - s3.amazonaws.com
                  - cloudformation.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: '*'
                  Resource: '*'
                    
    AppCodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        ServiceRole: !GetAtt CodePipelineServiceRole.Arn
        Cache:
          Type: S3
          Location: !Join [ "/", [ !Ref ArtifactBucket, "projectcache" ] ]
        Artifacts:
          Type: CODEPIPELINE
          Location: !Ref ArtifactBucket
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:2.0
          PrivilegedMode: true
        Source:
          Type: CODEPIPELINE
        TimeoutInMinutes: 15
        LogsConfig:
          CloudWatchLogs: 
            GroupName: sample-lambda-app-build-log-group
            Status: ENABLED
    
    CodeStarConnection:
      Type: 'AWS::CodeStarConnections::Connection'
      Properties:
        ConnectionName: GitHubToPipelineConnection
        ProviderType: GitHub
        
    AppPipeline: 
      Type: AWS::CodePipeline::Pipeline 
      Properties: 
        ArtifactStore:
          Location: !Ref ArtifactBucket
          Type: S3
        RoleArn: !GetAtt CodePipelineServiceRole.Arn
        Stages: 
          - 
            Name: Source 
            Actions: 
              - 
                Name: SourceAction
                ActionTypeId: 
                  Category: Source 
                  Owner: AWS 
                  Version: '1' 
                  Provider: CodeStarSourceConnection          
                OutputArtifacts: 
                  - 
                    Name: express-miniapp
                Configuration: 
                  ConnectionArn: !GetAtt CodeStarConnection.ConnectionArn
                  FullRepositoryId: edwardmercado/mercado-devops-challenge-tier-2
                  BranchName: main
                  OutputArtifactFormat: CODEBUILD_CLONE_REF
                RunOrder: 1 
          - 
            Name: Build 
            Actions: 
              - 
                Name: BuildAction 
                InputArtifacts: 
                  -
                    Name: express-miniapp
                OutputArtifacts:
                  - 
                    Name: express-miniapp-run
                ActionTypeId: 
                  Category: Build 
                  Owner: AWS
                  Version: 1 
                  Provider: CodeBuild
                Configuration: 
                  ProjectName: !Ref AppCodeBuildProject
                  PrimarySource: express-miniapp
                RunOrder: 1 
          # - 
          #   Name: Release 
          #   Actions: 
          #     - 
          #       Name: ReleaseAction
          #       InputArtifacts: 
          #         - 
          #           Name: express-miniapp-run
          #       ActionTypeId: 
          #         Category: Deploy
          #         Owner: AWS 
          #         Version: 1
          #         Provider: S3 
          #       Configuration: 
          #         BucketName: !Ref ImageBucket
          #         Extract: false
          #         ObjectKey: containerImage.zip
          #       RunOrder: 1

            