AWSTemplateFormatVersion: 2010-09-09
Description: Test for Lambda Layers
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdaStackName:
    Type: String
    Default: samplelambdastack
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
  ApprovalSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: edwardallenlearning@gmail.com
        Protocol: email
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
            - codebuild.amazonaws.com
            - codedeploy.amazonaws.com
            - s3.amazonaws.com
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
  AppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole:
        Fn::GetAtt:
        - CodePipelineServiceRole
        - Arn
      Cache:
        Type: S3
        Location:
          Fn::Join:
          - /
          - - Ref: ArtifactBucket
            - projectcache
      Artifacts:
        Type: CODEPIPELINE
        Location:
          Ref: ArtifactBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 15
      LogsConfig:
        CloudWatchLogs:
          GroupName: sample-lambda-app-build-log-group
          Status: ENABLED
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: GitHubToPipelineConnection
      ProviderType: GitHub
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location:
          Ref: ArtifactBucket
        Type: S3
      RoleArn:
        Fn::GetAtt:
        - CodePipelineServiceRole
        - Arn
      Stages:
      - Name: Source
        Actions:
        - Name: SourceAction
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: sample-app
          Configuration:
            ConnectionArn:
              Fn::GetAtt:
              - CodeStarConnection
              - ConnectionArn
            FullRepositoryId: edwardmercado/test
            BranchName: main
            OutputArtifactFormat: CODEBUILD_CLONE_REF
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: BuildAction
          InputArtifacts:
          - Name: sample-app
          OutputArtifacts:
          - Name: sample-app-build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          Configuration:
            ProjectName:
              Ref: AppCodeBuildProject
            PrimarySource: sample-app
          RunOrder: 1
      - Name: Deploy-Dev
        Actions:
        - ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: CloudFormation
          InputArtifacts:
          - Name: sample-app-build
          Configuration:
            ActionMode: CHANGE_SET_REPLACE
            Capabilities: CAPABILITY_NAMED_IAM
            ChangeSetName: pipeline-changeset-dev
            StackName:
              Fn::Join:
              - ''
              - - Ref: LambdaStackName
                - -DEV
            TemplatePath: sample-app-build::packaged-template.yaml
            RoleArn:
              Fn::GetAtt:
              - CodePipelineServiceRole
              - Arn
          RunOrder: 1
          Name: Generate-Change-Set-To-Dev
        - ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: CloudFormation
          Configuration:
            ActionMode: CHANGE_SET_EXECUTE
            ChangeSetName: pipeline-changeset-dev
            StackName:
              Fn::Join:
              - ''
              - - Ref: LambdaStackName
                - -DEV
          RunOrder: 2
          Name: Execute-Change-Set-To-Dev
      - Name: Review
        Actions:
        - Name: Review-Changes
          ActionTypeId:
            Category: Approval
            Owner: AWS
            Version: 1
            Provider: Manual
          Configuration:
            CustomData: Review changes for PROD deployments
            NotificationArn:
              Ref: ApprovalSNSTopic
          RunOrder: 1
      - Name: Deploy-Prod
        Actions:
        - ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: CloudFormation
          InputArtifacts:
          - Name: sample-app-build
          Configuration:
            ActionMode: CHANGE_SET_REPLACE
            Capabilities: CAPABILITY_NAMED_IAM
            ChangeSetName: pipeline-changeset-prod
            StackName:
              Fn::Join:
              - ''
              - - Ref: LambdaStackName
                - -PROD
            TemplatePath: sample-app-build::packaged-template.yaml
            RoleArn:
              Fn::GetAtt:
              - CodePipelineServiceRole
              - Arn
            ParameterOverrides: "{\n  \"Environment\" : \"prod\"\n}\n"
          RunOrder: 1
          Name: Generate-Change-Set-To-PROD
        - ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: CloudFormation
          Configuration:
            ActionMode: CHANGE_SET_EXECUTE
            ChangeSetName: pipeline-changeset-prod
            StackName:
              Fn::Join:
              - ''
              - - Ref: LambdaStackName
                - -PROD
          RunOrder: 2
          Name: Execute-Change-Set-to-PROD
