name: MirrorToCodeCommit 

on: [push, delete] 

jobs: 

  to_codecommit:                                         

    runs-on: ubuntu-18.04 

    steps: 

    - uses: actions/checkout@v1 

    - uses: pixta-dev/repository-mirroring-action@v1 

      with: 

        target_repo_url: 

          ssh://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test

        ssh_private_key: 

          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }} 

        ssh_username:                                    

          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}
